baseURL = "https://plumbmum.co.uk"
languageCode = "en-us"
title = "PlumbMum | Harrogate"
theme = "bootstrap-start"
publishDir = "docs"

[params]
  description = "Local harrogate plumber"
#  images = ["logo.jpg"]
#  startPageColumns = true
  welcomeText = "Welcome to plumbmum.co.uk Harrogate"
#  showGoogleSearch = true


[sitemap]
  changefreq = "weekly"
  priority = 0.5